(define (first items)
	(car (cdr (car (cdr (cdr items)))))
  )
(define (second items)
	(car (car items))
  )
(define (third items)
	(car (cdr (car (cdr (car (cdr (car (cdr (car (cdr (car (cdr items))))))))))))
  )
